AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Examples with scheduled functions using cron or rate syntax.

Resources:
  CronScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ScheduledQueryEvent:
          Type: Schedule
          Properties:
            # triggered every day at 12 pm
            Schedule: cron(0 12 * * ? *)

  RateScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ScheduledQueryEvent:
          Type: Schedule
          Properties:
            # triggered every day on the time when the event has been created (or last updated)
            Schedule: rate(1 day)
